web: java -jar target/cloud-client-api-0.0.0-SNAPSHOT.jar -Dspring-boot.run.profiles=default
process: java -jar target/cloud-client-api-0.0.0-SNAPSHOT-processingjob.jar -Dspring-boot.run.profiles=default
