"""
generate.py - take generic template and process to different languages.
"""

import shutil


LANGUAGES = ["python"]  # , "nodejs", "java"]
GENERATED_COMMENT = "Generated by 'make generate'. Do not manually edit.\n"

for lang in LANGUAGES:
    print(f"Processing {lang}")
    with open("app/templates/index.html.tmpl") as html:
        output = []

        output.append(f"<!--- {GENERATED_COMMENT} -->")
        for line in html.readlines():
            if "##" in line:

                # VALUE
                if "##VALUE" in line:
                    if lang == "python" or lang == "nodejs":
                        front_replace, back_replace = "{{ ", " }}"
                    elif lang == "java":
                        front_replace, back_replace = "${ ", "\}"

                    line = line.replace("##VALUE(", front_replace).replace(
                        ")##", back_replace
                    )

                if "##IF" in line:
                    if lang == "python":
                        front_replace, back_replace = "{% if ", " %}"
                    elif lang == "nodejs":
                        front_replace, back_replace = "\{\{\# if  ", " \}\}"
                    elif lang == "java":
                        front_replace, back_replace = 'th:if="${ ', "\}"

                    line = line.replace("##IF(", front_replace).replace(
                        ")##", back_replace
                    )

                if "##ELSE" in line:
                    if lang == "python":
                        replace = "{% else %}"
                    elif lang == "nodejs":
                        replace = "\{\{ else \}\}"
                    elif lang == "java":
                        replace = 'th:unless="$\{'
                    line = line.replace("##ELSE", replace)

                if "##ENDIF" in line:
                    if lang == "python":
                        replace = "{% endif %}"
                    elif lang == "nodejs":
                        replace = "\{\{/if\}\}"
                    elif lang == "java":
                        replace = ""
                    line = line.replace("##ENDIF", replace)

            output.append(line)

    html_output = f"app/{lang}/templates/index.html"

    with open(html_output, "w") as f:
        for line in output:
            f.write(line)

    print(f"Wrote {html_output}")
