"""
generate.py - take generic template and process to different languages.
"""

import difflib
import sys


# Language / Template folder name
TEMPLATES = {"python": "templates/index.html", "nodejs": "views/index.handlebars"}
# TODO(glasnt): Add when additional languages available.

for lang in TEMPLATES.keys():
    with open("app/templates/index.html.tmpl") as html:
        output = []

        output.append(f"<!--- Generated by 'make generate'. Do not manually edit. -->\n")
        for line in html.readlines():
            if "##" in line:

                # VALUE
                if "##VALUE" in line:
                    if lang == "python" or lang == "nodejs":
                        front_replace, back_replace = "{{ ", " }}"
                    elif lang == "java":
                        front_replace, back_replace = "${ ", "\}"

                    line = line.replace("##VALUE(", front_replace).replace(
                        ")##", back_replace
                    )

                if "##LIST" in line:
                    if lang == "python":
                        front_replace, back_replace = "{{ ", " }}"
                    elif lang == "nodejs":
                        front_replace, back_replace = "[{{ ", " }}]"
                    elif lang == "java":
                        front_replace, back_replace = "${ ", "\}"

                    line = line.replace("##LIST(", front_replace).replace(
                        ")##", back_replace
                    )

                if "##IF SQUIRRELS##" in line:
                    if lang == "python":
                        replacement = "{{ if squirrel_count > 0 }}"
                    elif lang == "nodejs":
                        replacement = "{{#if squirrel_count}}"
                    elif lang == "java":
                        replacement = "TOOD(java)"

                    line = line.replace("##IF SQUIRRELS##", replacement)

                if "##ELSE" in line:
                    if lang == "python":
                        replace = "{% else %}"
                    elif lang == "nodejs":
                        replace = "{{else}}"
                    elif lang == "java":
                        replace = 'th:unless="$\{'
                    line = line.replace("##ELSE", replace)

                if "##ENDIF" in line:
                    if lang == "python":
                        replace = "{% endif %}"
                    elif lang == "nodejs":
                        replace = "{{/if}}"
                    elif lang == "java":
                        replace = ""
                    line = line.replace("##ENDIF", replace)

            output.append(line)

    html_output = f"app/{lang}/{TEMPLATES[lang]}"

    # Check if any changes are required to be made, error 1 if updates needed
    if "--validate" in sys.argv:
        with open(html_output, "r") as f:
            original = f.readlines()

        diffs = []
        for line in difflib.unified_diff(
            original, output, fromfile=html_output, tofile=f"(new {html_output})"
        ):
            diffs += line

        if len(diffs) == 0:
            print(f" {lang} generated output identical. No differences.")
        else:
            print("\n❌ {lang} generated output different. Need to run `make generate`.\n")
            print("".join(diffs))
            sys.exit(1)

    else:
        # Write results
        with open(html_output, "w") as f:
            for line in output:
                f.write(line)

        print(f"Wrote {html_output}")
